import pyautogui
import time
import pyperclip
from openai import OpenAI
import json

client = OpenAI(api_key="sk-1234abcd1234abcd1234abcd1234abcd1234abcd")

def is_last_message_from_kakashi(chat_text: str) -> bool:
    if not chat_text:
        return False

    lines = [line for line in chat_text.splitlines() if line.strip()]
    if not lines:
        return False

    return "] Kakashi:" in lines[-1]


pyautogui.click(1639, 412)
time.sleep(0.5)

while True:
    time.sleep(0.5)

    # Click chat
    pyautogui.click(1639, 412)
    time.sleep(0.5)

    # Select chat text
    pyautogui.moveTo(1900, 1060)
    pyautogui.dragTo(414, 46, duration=1, button='left')
    time.sleep(0.3)

    # Copy
    pyautogui.hotkey('ctrl', 'c')
    pyautogui.click(1900, 1060)
    time.sleep(0.3)

    chat_history = pyperclip.paste()

    print("Copied Text:")
    print(chat_history)

    if is_last_message_from_kakashi(chat_history):
        print("Last message is from Kakashi, skipping response.")
        time.sleep(2)
        continue

    tools = [
        {
            "type": "function",
            "function": {
                "name": "get_command",
                "description": "Naruto: I’m Naruto Uzumaki! Always energetic, big dreams of becoming Hokage, never give up, and I chat loudly, honestly, and straight from the heart — believe it!",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "sign": {
                            "type": "string",
                            "description": "An astrological sign like Taurus or Aquarius",
                        },
                    },
                    "required": ["sign"],
                },
            }
        }
    ]

    def get_command(sign):
        return f"{sign}: Next Tuesday you will befriend a baby otter."

    input_list = [
        {"role": "user", "content": "[7:12 am, 14/01/2026] Naruto: Kakashi-sensei! Good morning dattebayo!"},
        {"role": "user", "content": "[7:13 am, 14/01/2026] Kakashi: Morning, Naruto. You’re unusually energetic today."},
        {"role": "user", "content": "[7:14 am, 14/01/2026] Naruto: I couldn’t sleep! I was thinking about becoming Hokage 😤"},
        {"role": "user", "content": "[7:15 am, 14/01/2026] Kakashi: That’s an ambitious dream. Are you training seriously for it?"},
        {"role": "user", "content": "[7:16 am, 14/01/2026] Naruto: Of course! I’ll prove everyone wrong, believe it!"},
        {"role": "user", "content": "[7:17 am, 14/01/2026] Kakashi: Words are easy. Consistency is harder."},
        {"role": "user", "content": "[7:18 am, 14/01/2026] Naruto: Then I’ll train even harder! You’ll see, sensei!"}
    ]

    response = client.responses.create(
        model="gpt-5",
        tools=tools,
        input=input_list,
    )

    input_list += response.output

    for item in response.output:
        if item.type == "function_call" and item.name == "get_command":
            args = json.loads(item.arguments)
            command = get_command(args["sign"])
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({"command": command})
            })

    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with a horoscope generated by a tool.",
        tools=tools,
        input=input_list,
    )

    reply_text = response.output_text
    pyperclip.copy(reply_text)

    print("Final output:")
    print(reply_text)

    time.sleep(3)
    pyautogui.click(1030, 1035)
    time.sleep(0.2)
    pyautogui.hotkey('ctrl', 'v')
    time.sleep(0.2)
    pyautogui.press('enter')
